




print ("hello" + "world")
number = (1+1+1)
print (f"hello + {number}")
print (f"{number} + hello world")
my_list = [1,2,3,4,5,6,7,8,9,10]
Unpair_list =  [3,5,7,9]
print (my_list + Unpair_list)
print (f"esta es la lista  {my_list}")
number_1 = float (number // 5)
number_2 = (3*3)
print ( zip,{number_1},{number_2})
verdadero = True
falso = False
resultado = 2<1
if resultado:
    print("la condicion es verdadera")
else:
    print("la condicion es falsa")

print (bool(0),bool(10))

